nelmio_cors:
  defaults:
        origin_regex: true	    origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']	    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']	    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ['Content-Type', 'Authorization']	    allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ['Link']	    expose_headers: ["Link"]
        max_age: 3600	    max_age: 3600
                