nelmio_cors:
        defaults:
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            expose_headers: ['*']
            max_age: 0
            hosts: ['*']
            origin_regex: true
            forced_allow_origin_value: ~
        paths:
            '^/':
                