nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/api/':
                allow_origin: ['http://54.164.153.184']
                allow_headers: ['X-AUTH-TOKEN']
                allow_control_allow_credentials : true
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['http://54.164.153.184']
                allow_control_allow_credentials : true
                allow_headers: ['content-type', 'authorization']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                