<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvTg2j8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvTg2j8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZvTg2j8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZvTg2j8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZvTg2j8\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZvTg2j8',
    'container.build_id' => '8315736e',
    'container.build_time' => 1586442133,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvTg2j8');
